import React, { Fragment } from "react";
import Header from "./Header";
import Head from "next/head";

export const Layout = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Liara Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="w-full h-[975px] fixed left-0 z-[-1]"
        style={{
          background:
            "radial-gradient(87.68% 101.73% at 51.86% -0.36%, rgba(32, 106, 190, 0.20) 0%, rgba(13, 30, 51, 0) 100%)"
        }}
      />
      <Header />
      {children}
    </Fragment>
  );
};
